development:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: MC_development
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: MC_production
  pool: 5
  username: root
  password:
  host: localhost
  
va:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: VA_development
  pool: 5
  username: root
  password:
  host: localhost
  
ref_area:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: ref_area_dev
  pool: 5
  username: root
  password:
  host: localhost  
