login: &login
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 
  host: localhost
     
development:
  database: mc_development
  <<: *login
  
production:
  database: mc_production
  <<: *login
    
va_development:
  database: va_development
  <<: *login

va_production:
  database: va_production
  <<: *login
    
op_development:
  database: op_development
  <<: *login

op_production:
  database: op_production
  <<: *login
        
ref_area:
  database: ref_area_dev
  <<: *login