development:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: mc_development
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: mc_production
  pool: 5
  username: root
  password:
  host: localhost
  
va:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: op_development
  pool: 5
  username: root
  password:
  host: localhost

op:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: op_development
  pool: 5
  username: root
  password:
  host: localhost
    
ref_area:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: ref_area_dev
  pool: 5
  username: root
  password:
  host: localhost  
